name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Instala Flutter (estable)
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'

      # Instala dependencias
      - name: Install dependencies
        run: flutter pub get

      # Analiza el c√≥digo
      - name: Analyze project source
        run: flutter analyze

      # Corre los tests
      - name: Run tests
        run: flutter test
